#ifndef Generator_h
#define Generator_h

#include <string>

using namespace std;

namespace util
{

	/* An expression that generates a sequence of string values, following some distribution (Uniform, Zipfian, Sequential, etc.) */
	class Generator
	{
	public:
        /* Generate the next string in the distribution. */
        virtual wstring nextString() = 0;

		/**
         * Return the previous string generated by the distribution; e.g., returned from the last nextString() call.
         * Calling lastString() should not advance the distribution or have any side effects. If nextString() has not yet
         * been called, lastString() should return something reasonable.
         */
		virtual wstring lastString() = 0;
	};


}

#endif /* Generator_h */
